name: Test Action

on:
  project_card:
    types: [moved]

jobs:
  github_deets:

    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
    - uses: andymckay/labeler@1.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        add-labels: "bug"

