name: Test Action

on:
  project_card:
    types: [moved]

jobs:
  github_deets:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo Committed By: ${{ github.actor }}
