name: Test Action

on:
  project_card:
    types: [moved]

jobs:
  github_deets:

    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
    - uses: andymckay/labeler@1.0.0
    - name: Run a one-line script
      run: echo Hello, world!
    - name: labeltest
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        add-labels: "needs-triage, bug"
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo ${{ github.event.project_card.content_url }}
